### ISSUE TITLE
double recipes

### ISSUE THREAD

**Issue by Lucky-56** [AstralOrdana/molten-metals#2]
although both recipes are tag based, both are loaded at the same time

Versions:
Minecraft version: 1.20.1
Molten Metals version: 0.1.3
Forge version: 47.2.32

![2024-05-18_00 50 19](https://github.com/AstralOrdana/molten-metals/assets/55949451/b852f84d-5ba9-4705-90ef-49ba6838c06a)
![2024-05-18_00 50 21](https://github.com/AstralOrdana/molten-metals/assets/55949451/08bb56fc-b32a-497a-a3c5-d4cde3adac44)

**Comment by Lucky-56** [comment]
exists for all silver related recipes

**Comment by AstralOrdana** [comment]
this is a natural concequence of loading oreganized and galosphere at the same time, the recipes dont interfere and fixing this would be non-trivial

**Comment by Lucky-56** [comment]
why have two recipes in the first place tho, as they literally added tags for this

sorry, just seems sloppy to me

**Comment by AstralOrdana** [comment]
the recipe does use tags, and as you can see they are functionally identical with their inputs and outputs. the reason they exist as two separate recipes is their loading conditions, one is added if oreganized is loaded, the other if it detects galosphere. forge recipe conditions don't let you do an any-of check so this is the best i can do.

**Comment by AJBuilder** [comment]
Does the `forge:or` condition not work? Am I missing something?

I made this change on my fork. Pr is https://github.com/AstralOrdana/molten-metals/pull/8
