### ISSUE TITLE
[Suggestion] Nuggets can only be made into ingots by melting them

### ISSUE THREAD

**Issue by MrRedstoneToGo** [AstralOrdana/molten-metals#4]
I think smelting is all well and good, but I still don't see any real added value in using smelting at all! It's a bit more expensive with the Blaze Burner than simply throwing the ores into the furnace. So I was thinking, what if you could make ingots into nuggets, but not back! I mean, you break an ingot and just put it back together seamlessly and it holds? To turn them back into ingots, you have to melt them down. The same could apply to armor.

**Comment by AstralOrdana** [comment]
a custom datapack could be made to create that functionality but it wont be added to the mod

**Comment by BugInYourCode01** [comment]
You could also make benefits when melting ores / crushed ores to get people to melt them
